default: &default
  adapter: jdbcmysql
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: pin@2020
  host: localhost
  port: 3306

development:
  <<: *default
  database: cloudbroker

test:
  <<: *default
  database: cloudbroker

production:
  <<: *default
  database: cloudbroker